# Overview: Cloud Build build pipeline with Cloud Deploy release using git tag.

substitutions:
  _APP_NAME: hello
  _PIPELINE_NAME: deploy-demo-pipeline

steps:

  # Go test
  - id: test
    name: us-docker.pkg.dev/cloudy-demos/hub/golang@sha256:403f48633fb5ebd49f9a2b6ad6719f912df23dae44974a0c9445be331e72ff5e
    env:
    - GO111MODULE=on
    entrypoint: /bin/bash
    dir: app
    args:
    - -c
    - |
      go test -short -count=1 -race -covermode=atomic -coverprofile=cover.out ./...

  # Build image
  - id: build
    name: gcr.io/cloud-builders/docker@sha256:e4516d42f7930fee639333151672caa7fdc35c7f9b5e7bb4b90d12d77e775a34
    entrypoint: /bin/bash
    waitFor:
    - test
    dir: app
    args:
    - -c
    - |
      docker build --build-arg VERSION=${TAG_NAME} \
        -t "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_APP_NAME}:${COMMIT_SHA}" \
        -t "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_APP_NAME}:${TAG_NAME}" \
        .
  
  # Publish image, get digest, and save it to file.
  # Digest because tags aren't (really) cryptographically verifiable.
  - id: publish
    name: gcr.io/cloud-builders/docker@sha256:e4516d42f7930fee639333151672caa7fdc35c7f9b5e7bb4b90d12d77e775a34
    entrypoint: /bin/bash
    waitFor: 
    - build
    dir: app
    args:
    - -c
    - |-
      docker push "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_APP_NAME}:${TAG_NAME}"
      docker image inspect "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${_APP_NAME}:${TAG_NAME}" \
        --format '{{index .RepoDigests 0}}' > image-digest.txt
      cat image-digest.txt

  # Generate Software Bill of Materials (SBOM).
  # Generate SBOM file for all image layers in JSON format (SPDX schema), 
  # and creates attestation for that container image with the SBOM as predicate
  # Future: Automatically SBOM generation in CA. 
  - id: sbom
    name: us-docker.pkg.dev/cloudy-tools/builders/sbominator@sha256:508ebd72e7b83fa3db15419820afa2c8eeff9be2111dd42bb7980c2fdddfd0f4
    entrypoint: /bin/bash
    waitFor:
    - publish
    dir: app
    env:
    - PROJECT=$PROJECT_ID
    - KEY=$_KMS_KEY_NAME
    - COMMIT=$COMMIT_SHA
    - VERSION=$TAG_NAME
    - ATTESTOR=$_BIN_AUTHZ_ID
    args:
    - -c
    - |-
      builder $(cat image-digest.txt)

  # Generate Software Bill of Materials (SBOM) for all image layers in SPDX/JSON format.
  # - id: sbom2
  #   name: us-docker.pkg.dev/cloudy-demos/hub/anchore/syft@sha256:58cdb09e9a6d196d8e330e46d164d76aa397bba65e00782a2f8e8b923656f21d
  #   waitFor:
  #   - publish
  #   dir: app
  #   env:
  #   - _DIGEST=$(cat image-digest.txt)
  #   args:
  #   - -o=spdx-json
  #   - -s=AllLayers
  #   - --file=./report.json
  #   - $(cat image-digest.txt)
  #   - ${_DIGEST}

  # Test against my vulnerability policy.
  # For stability of the demo uses a pre-built image.
  # See the grafeas/kritis for instruction on how to build your own signer.
  # https://github.com/grafeas/kritis/blob/master/docs/signer.md
  # Check-based policies
  # Future: Call to check-based policy API in BinAuthz (consistent controls)
  - id: scan
    name: us-west1-docker.pkg.dev/cloudy-demos/tools/kritis-signer@sha256:51cec6d7d9390ea8ab9eb3b62f42c5cc69eaa048fcf46b8655fcf205e38a7fe2
    entrypoint: /bin/bash
    waitFor:
    - publish
    args:
    - -c
    - |-
      /kritis/signer \
        -mode=check-and-sign -v=10 -alsologtostderr \
        -image=$(/bin/cat app/image-digest.txt) \
        -policy=policy/vulnz-signing-policy.yaml \
        -note_name=${_NOTE_NAME} \
        -kms_key_name=${_KMS_KEY_NAME} \
        -kms_digest_alg=${_KMS_DIGEST_ALG}

  # Attest image with BinAuthz (attestation to X)
  # Future: Could be unnecessary, given SBOM/Provenance/Vulnerability-based policy checks
  - id: attest
    name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:5e69d0a7e3c1206c0a2f48f6299487d7f7c34c8b228e809b1000b032cb33d987
    entrypoint: /bin/bash
    waitFor:
    - sbom
    - scan
    args:
    - -c
    - |-
      gcloud beta container binauthz attestations sign-and-create \
        --attestor projects/${PROJECT_ID}/attestors/built-by-cloud-build \
        --artifact-url $(cat app/image-digest.txt) \
        --keyversion ${_KMS_KEY_NAME}

  # Create release in Google Cloud Deploy
  - id: release
    name: gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:5e69d0a7e3c1206c0a2f48f6299487d7f7c34c8b228e809b1000b032cb33d987
    entrypoint: /bin/bash
    waitFor:
    - attest
    dir: app
    args:
    - -c
    - |
      gcloud deploy releases create rel-${SHORT_SHA} \
      --delivery-pipeline ${_PIPELINE_NAME} \
      --region ${LOCATION} \
      --annotations "commitId=${REVISION_ID},tag=${TAG_NAME}" \
      --images "${_APP_NAME}=$(cat image-digest.txt)"

images:
- ${LOCATION}-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$_APP_NAME:$TAG_NAME

options:
  # Verify generation of attestations and provenance metadata for this build.
  # Otherwise, GCB generates provenance for global builds only.
  requestedVerifyOption: VERIFIED
  sourceProvenanceHash: ["SHA256"]
  pool:
    name: 'projects/$PROJECT_ID/locations/$LOCATION/workerPools/$_POOL_NAME'

tags:
- demo